#pragma once

#define MASTER_RIGHT
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_INVERT_Y 1
#define POINTING_DEVICE_INVERT_X 1
#define SPI_DRIVER SPID1
#define SPI_MISO_PIN GP12
#define PMW33XX_CS_PIN GP13
#define SPI_SCK_PIN GP14
#define SPI_MOSI_PIN GP15
//#define PMW33XX_LIFTOFF_DISTANCE 0x06
//#define PMW33XX_CPI 1600

#define SCROLL_DIVIDER 12
#define CPI_1 2000
#define CPI_2 4000
#define CPI_3 8000

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 2
